### ISSUE TITLE
Communication over Serial Port

### ISSUE THREAD

**Issue by ummarbhutta** [sympthom/Valley.Net.Protocols.MeterBus#1]
I want to use `MBusMaster` with Serial port, From current code it looks like it is not possible. Would be a useful feature when using UART MBus receivers.

**Comment by sympthom** [comment]
That can easily be done by extending the library Valley.Net.Bindings. If you want to send a pull request I would be happy to include it.

Cheers,
Martin

**Comment by sympthom** [comment]
Serial capability has been added.
