### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by coskunergan** [sympthom/Valley.Net.Protocols.MeterBus#2]
I've detected an error on this class. and I fixed it.

(update line 174)
case DataTypes._24_Bit_Integer:	
System.Diagnostics.Debug.Assert(value.Data.Length == 3);
//record.Value = BitConverter.ToInt32(new byte[] { 0 }.Concat(value.Data).ToArray(), 0); // Orj. 
#region Coskun edit
byte[] temp = new byte[4];
temp[0] = value.Data[0];
temp[1] = value.Data[1];
temp[2] = value.Data[2];
record.Value = BitConverter.ToInt32(temp, 0);//coskun
#endregion
break;

for example;
input value = 0x112233;
bug result = 0x11223300;
update result=0x00112233;

**Comment by sympthom** [comment]
Thanks for your input. Can you please provide with sample data in hex format?

Cheers,
Martin

**Comment by sympthom** [comment]
Above code was merged into master.
