### ISSUE TITLE
wM-Bus Support

### ISSUE THREAD

**Issue by rahimshahid** [sympthom/Valley.Net.Protocols.MeterBus#3]
Is it possible to use this library with wM-Bus, currently it looks like wM-Bus is not supported, am I right?
If yes, is there a possibility if you can add support for wM-Bus in this library?

**Comment by sympthom** [comment]
EN13757-4 can be implemented by reusing a the code in the library. Feel free to send me a pull request.

Cheers,
Martin

**Comment by m0veax** [comment]
Hey, sry for reactivating this issue.

Could you give us a hint, which parts could be reused?

We are looking for a EN13757-4 parser and are currently considering if we could do a pull request here :)
