### ISSUE TITLE
Not supported frames

### ISSUE THREAD

**Issue by erdemts** [sympthom/Valley.Net.Protocols.MeterBus#5]
We are testing library for data below:
"68 47 47 68 08 FD 72 03 01 47 01 AE 4C 51 07 6C 60 00 00 0E 13 30 54 46 00 00 00 0E 93 3C 29 00 00 00 00 00 04 3B 21 00 00 00 0C 78 03 01 47 01 0C FD 10 00 00 00 00 04 6D 0A 12 6D 2C 0D FD 0C 09 4D 20 41 49 44 49 53 45 52 1F ED 16"

Library couldn't parse this frame. Could you fix it, please?
Regard,

**Comment by sympthom** [comment]
You are more than welcome to send me a pull reqeust for the test case above.

Cheers,
Martin

**Comment by sympthom** [comment]
Seems like the test data stream is corrupt. It may lack the last 2 bytes as it's suppose to have another _16_Bit_Integer in length.

**Comment by erdemts** [comment]
![WhatsApp Image 2020-03-23 at 22 26 57](https://user-images.githubusercontent.com/11312452/77356474-6f977280-6d57-11ea-90bb-f6c2ad95eb09.jpeg)

Thanks for you reply. I checked this frame another library. I can share this library with you. 
We like your library:)
